POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvb2xtYW4iLCJpZCI6IjVmYTgwYzQ3MzQxMGQzMGZlYzRmMTUxMyIsImlhdCI6MTYwNDg0OTIxOX0.dlJ3PmBrsDS9LFOcgDa5b9yh6dxXhmcW25tQyZgYDpg

{
    "title" : "Dummy book",
    "author" : "Nobody",
    "url" : "www.Nobody.com",
    "likes": 9999
}